comment:
  footer: >
    ---
    > I am a bot, and this is an automated message ðŸ¤–
labels:
  - name: âœ–ï¸ Invalid
    labeled:
      pr:
        action: close
        body: >
          Thank you @{{ pull_request.user.login }} for contributing to this repository.
          Your Pull Request has been marked as invalid.

          Please ensure you follow the pull request template, provide all relevant info,
          and target the correct branch. `staging` is the default target branch, `release` should only be targeted for important hotfixes.

          If you have any questions, feel free to reach out.

  - name: â›” Don't Merge
    labeled:
      pr:
        body: >
          This PR has been temporarily blocked from merging.

  - name: ðŸ’¥ðŸ’£ Breaking Changes
    labeled:
      pr:
        body: >
          This PR is marked as containing one or more breaking changes.

          Please make sure that those are documented accordingly and steps to inform users at release are prepared.

  - name: â›” Waiting For External/Upstream
    labeled:
      pr:
        body: >
            This PR is awaiting external or upstream changes or approval.
            It can only be merged once those changes have been implemented and approved.
            Please inform us of any progress on the upstream changes or approval.
